### ISSUE TITLE
Add custom informations request on Contact form

### ISSUE THREAD

**Issue by lcoenen** [Whichost/frontend#136]
We will have to create different forms in the Contact form to gather different informations: 

- General enquiries
- Feedback
- Payement information change
- Claim my listing

**Comment by RohrerHope** [comment]
@lcoenen 

I remember that I added comments to an issue in which I explained each of the purposes of the contact form and the questions for each one, but I can't find it.

Do you know where they are? 

Thanks.

**Comment by RohrerHope** [comment]
Found it.

Issue #113 the comments were hidden.

Do you want to keep them there? Or do you prefer that I transfer that information into this issue?

**Comment by lcoenen** [comment]
@RohrerHope please copy-paste them here, this will be easier :)

**Comment by RohrerHope** [comment]
> @RohrerHope please copy-paste them here, this will be easier :)

**Here it is**

Ideas for the dropdown menu:

Title of the field: Select your contact purpose

- General Inquiry
- Booking a pub
- Listing a space
- Claiming a listing
- Changing the payment information
- Corporate Benefit Inquiry

What happens when they choose each of them?

- General Inquiry
- Booking a pub
- Listing a space

Contact form remains the same. No new field needs to be presented.

- Claiming a listing

Contact form adapts and adds new fields (all mandatory):
1. Your name (text field)
1. Your last name (text field)
1. Your email address (text field with validation for proper email address)
1. Listing's name (text field)
1. Are you the owner or manager of the pub? (multiple options question with 2 options: Owner, Manager. Only one option can be selected.)
1. What's the pub's phone number? (text field controlling the number of characters to be entered)
1. Please indicate if the pub has any of the following: (checkbox options with 4 options: Website, Facebook page, Twitter, Instagram. More than one option can be selected.)
1. To claim your listing you must agree to our Terms & Conditions of Service, together with our Privacy Policy. (checkbox with only one checkbox option: I agree. The T&Cs and Privacy Policy must be hyperlinked to their corresponding pages.)

Best case scenario here is that as they are typing the name of the listing, we show results below it, with the listings that match the text they are inputting. Much like what Google does in Google Maps when you start typing an address and it starts to show results that match your text.

- Changing the payment information

Contact form adapts and adds new fields:
1. Account email (text field with validation for proper email address)
1. Listing's name (text field)
1. New listing IBAN (text field with validation for proper IBAN format)

1.1 Note: Best case scenario here is that the account email is already populated if the user is logged in.

2.1 Note: Best case scenario here is that as they are typing the name of the listing, we show results below it, with the listings that match the text they are inputting. Much like what Google does in Google Maps when you start typing an address and it starts to show results that match your text.

3.1 Note: Best case scenario here is that the IBAN field validates the IBAN format. IBANs have an international format and we can validate against it.

- Corporate Benefit Inquiry

Contact form adapts and adds new fields:
1. Your name (text field, mandatory)
1. Organisation (text field, mandatory)
1. Number of employees (dropdown field: options here: https://developer.linkedin.com/docs/reference/company-size-codes#, mandatory)
1. Website (URL field, mandatory)

Thank you 👍

**Comment by lcoenen** [comment]
We will have to remember to adjust the links in `FAQPage`.

**Comment by lcoenen** [comment]
Here is the list here: https://github.com/Whichost/frontend/issues/113#issuecomment-487271349

**Comment by lcoenen** [comment]
Here's the requirement list: 

- The correct set of fields should be shown depending on the `enquiry` field.
- The email template should react accordingly.
- The mail address field should be grabbed from connected user if any.
- The enquiry field should react to the URL.
- The IBAN should be validated.
- The links accross the website should be updated.

**Comment by lcoenen** [comment]
> 1.1 Note: Best case scenario here is that the account email is already populated if the user is logged in.

I will try to implement that, but that will take a little bit of time.

> Best case scenario here is that as they are typing the name of the listing, we show results below it, with the listings that match the text they are inputting. Much like what Google does in Google Maps when you start typing an address and it starts to show results that match your text.

This is non-trivial. If you want this, please create a separate issue :)

> 3.1 Note: Best case scenario here is that the IBAN field validates the IBAN format. IBANs have an international format and we can validate against it.

This is trivial and should be implemented quickly.

**Comment by lcoenen** [comment]
> To claim your listing you must agree to our Terms & Conditions of Service, together with our Privacy Policy. (checkbox with only one checkbox option: I agree. The T&Cs and Privacy Policy must be hyperlinked to their corresponding pages.)

For consistency reasons, I will not implement a checkbox, but will add a message above the button as it is shown in the Sign up Page: 

![image](https://user-images.githubusercontent.com/1237971/57324592-03d8f680-7100-11e9-8c25-f4e1615718e7.png)

**Comment by lcoenen** [comment]
> Contact form adapts and adds new fields:
> 
> Account email (text field with validation for proper email address)
> Listing's name (text field)
> New listing IBAN (text field with validation for proper IBAN format)
> 

For security reasons, I think we shouldn't ask for the account email. We are already asking for their contact email address and it should be the same - otherwise, it could be a fraud.

**Comment by lcoenen** [comment]
**What have been done**: Finished the contact form
**Pushed to**: `add-custom-informations-request-on-contact-form`
**Tag somebody**: @RohrerHope 
**PR**: #193 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by lcoenen** [comment]
**What have been done**: Add interactions scenarios into the Contact Us form
**Pushed to**: `add-custom-informations-request-on-contact-form`
**Tag somebody**: @Shane-Walsh 
**PR**: #209
