### ISSUE TITLE
Delete point 3.3 from Deals T&C

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#163]
**What's to be corrected**: 

Point 3.3 (and its 3.3.1) to be deleted from the T&Cs inside the "Birthday Gift" and the "Corporate Benefit".

Why?

Because we will remove the reference in the listings that they are managed by Whichost, together with deleting the URL to claim the listing from the description.

We will instead notify users of a refund or credit when their booking request is accepted. That's when we will inform them, but in the meantime, we will remove these pieces of information to reduce confusion.

**How should it look like (screenshot or sketch)**:

T&Cs for both the "Birthday Gift" and "Corporate Benefit" should no longer have the point 3.3 (and the 3.3.1).

**How should it work (write use case)**: N/A. This is only a change in text.

Thanks 👍 

**Priority (tag accordingly):** `urgent`
**Domain (tag accordingly):** `frontend`
**Branch**: `hotfix-delete-point-3-3-from-deals-t-c`

**Work on it**

- Work on `master`
- Tag with `ongoing` and move the card to `ongoing`.
- Correct the default
- Commit your work
- Create a PR (if it's `urgent`) and ask for validation. Move the card to `staged`.
- Close the issue if all the work have been done

**Comment by lcoenen** [comment]
**What have been done**: Removed point 3.3 from T&C
**Pushed to**: `delete-point-3-3-from-deal-t-c`
**Tag somebody**: @RohrerHope 
**PR**: #165 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
