### ISSUE TITLE
Change back to "Employees Benefit"

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#164]
**What's to be fixed**:

@lcoenen 

I have mentioned this before. There are discrepancies between master and staging and sometimes staging has old information that should not be pushed to master.

You have told me not to worry, that the versions will match and that the discrepancy in staging will not be pushed to master, and that everything will balance out.

This is not happening and I will ask to please stop this!

The Employees Benefit page was fine in Master, saying Employees Benefit.

Then on staging, I mentioned that it was saying Employee Benefit and you told me not to worry, that that information would not be pushed to master.

This is what it's in master now:

![Screen Shot 2019-04-28 at 12 09 12](https://user-images.githubusercontent.com/39112974/56863509-d62cd880-69ae-11e9-8519-8786a30910d6.jpg)

How am I to have peace of mind in the future that discrepancies will not be pushed to master?

**What's the expected behaviour:**

Discrepancies should not be pushed to master! 

It's not Employee Benefit, it's Employees Benefit. We had already changed this and it was fine, and now it's back to Employee Benefit after our latest push, in which I mentioned the message on staging!

**What happens in reality (screenshot):**
**Priority (tag accordingly):** `urgent` 
**Domain (tag accordingly):** `frontend`
**Branch**: `hotfix-change-back-employee-benefits-2.1.x`

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope You're entirely right, that is a caveat in our process. Yesterday, i had to fix the double registration issue again, because `staging` was behind `master` and to be honest the Footer is a mess. I sometime get confused between the terminology. Here are three solutions I can think of:

- We should consider having some sort of reference document about the terminology we're using.
- Keeping track of what version we're using (through version number) would allow us to check that we're working on the right version and that we won't erase previous change. For each change to `master`, we increment the version.

**Comment by lcoenen** [comment]
**What have been done**: We change capitalisation of Deals labels (issue #164)
**Pushed to**: `hotfix-change-back-employees-benefits-2.1.x`
**PR**: #170 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly @lcoenen
