### ISSUE TITLE
Remove FAQ from FAQ Title

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#174]
**What's the improvement**: 

In the FAQ page, the title says "Frequently Asked Questions (FAQ)".

People already know what FAQ is so adding it to the title, next to the full expression of it, it does not add value, and it does add visual noise.

![faq in title](https://user-images.githubusercontent.com/39112974/56881658-092ba680-6a59-11e9-8fa7-bf1e8ce8165b.jpg)

**How should it look like (screenshot or sketch)**:

![no faq in title](https://user-images.githubusercontent.com/39112974/56881702-295b6580-6a59-11e9-9333-1a8f954b5b83.jpg)

**How should it work (write use case)**:

N/A. This is text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version) Dell, Windows 10, Chrome, latest version.
**Branch**: staging 

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope This is a trivial change.

**Comment by lcoenen** [comment]
**What have been done**: We removed FAQ label from FAQ title.

![image](https://user-images.githubusercontent.com/1237971/56975241-4763bb80-6b68-11e9-870d-73d00d7d9b85.png)

**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.
