### ISSUE TITLE
Change Providers to Publicans

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#175]
**What's the improvement**: 

It will come the day in which we will have more than one type of business operating on our platform. Until that day comes, we will be working with publicans for some time. So everywhere we should talk about publicans, and not providers.

Providers, for now, is a term we should use only internally.

So anywhere where we mention providers, we should be saying publicans.

![providers to publicans](https://user-images.githubusercontent.com/39112974/56882014-2dd44e00-6a5a-11e9-8406-1ecf375bc529.jpg)

**How should it look like (screenshot or sketch)**:

This is an example of the Guide page for publicans. Please make sure that if you have added providers in other parts of the platform that you change them to publicans.

![publicans](https://user-images.githubusercontent.com/39112974/56882042-45133b80-6a5a-11e9-97c6-3ee8b3ee0b26.jpg)

**How should it work (write use case)**:

N/A, this is a text improvement.

**Priority (tag accordingly):** Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Dell, Windows 10, Chrome, latest version.
**Branch**: staging

**Work on it**

- Derive the branch from `staging`. 
- Tag with `ongoing` and move the card to `ongoing`.
- Develop the feature
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue if all the work have been done

** Validate **

- Check on mobile and on desktop if the feature have been correctly implemented.
- If everything is working fine, move the card to`accepted` column.
- If the feature isn't completely implemented, re-open the issue with a comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope, this is a trivial change.

**Comment by lcoenen** [comment]
**What have been done**: 
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 
**Where to test**: https://whichost-frontend-staging.herokuapp.com/help/providers-guidebook

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

**Comment by buckwierd** [comment]
The issue has been implemented/fixed correctly.
