### ISSUE TITLE
Fix Deals help page not correctly selected

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#176]
**What's to be fixed**:

On the left side menu (desktop view), when we select an item from that menu, it's highlighted and there's a vertical black bar that also indicates that we are seeing that page, as seeing here:

![example of menu hightlight](https://user-images.githubusercontent.com/39112974/56882266-09c53c80-6a5b-11e9-8852-bc4a5a2e7346.jpg)

However, on that same page when we click on Deals, that highlighting is gone. None existent.

![No menu selection highlight](https://user-images.githubusercontent.com/39112974/56882293-1ba6df80-6a5b-11e9-83e9-f36102d15e3e.jpg)

**What's the expected behavior:**

When clicking on any menu item, they all should behave the same. In this case, the Deals menu item must be highlighted when selected, and the black bar next to it should also show.

**What happens in reality (screenshot):**

There's no highlighting of the menu item selected, and no vertical black bar next to it.

![No menu selection highlight](https://user-images.githubusercontent.com/39112974/56882363-44c77000-6a5b-11e9-95d9-11d9746b7d60.jpg)

**Priority (tag accordingly):**Regular
**Domain (tag accordingly):** Frontend
**Tested on:** (platform, OS, browser, version): Dell, Windows 10, Chrome, latest version.
**Branch**: hotfix-deals-menu-highlight

**Work on it**

- Derive the branch from `master`. Prefix it with `hotfix-`.
- Tag with `ongoing` and move the card to `ongoing`.
- Fix the issue
- Commit your work
- Create a PR and ask for validation. Move the card to `staged`.
- Ask for validation.
- Close the issue

** Validate **

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. Move the card to `have issues` column.

Please follow https://github.com/Whichost/frontend/wiki/Git-workflow

**Comment by lcoenen** [comment]
@RohrerHope please use indicative present in issue titles.

**Comment by lcoenen** [comment]
**What have been done**: We fixed the selected test in `HelpCenter/DealsHelpPage/DealsHelpPage.js`
**Pushed to**: `fix-deals-help-page-not-correctly-selected`
**Tag somebody**: @RohrerHope 
**PR**: #176

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.
