### ISSUE TITLE
Title of deals hidden when clicking on the corresponding button

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#51]
@buckwierd 

In the deals page, we have 3 buttons, one for each type of deal.

This is how it looks:
![screen shot 2019-02-12 at 18 02 19](https://user-images.githubusercontent.com/39112974/52657424-8e8aca80-2ef0-11e9-91c4-57d99c928edb.jpg)

When I click on the Birthday Deal (as an example), the page scroll down, but it does so much that the tile of the deal is hidden, as shown in the image below:
![screen shot 2019-02-12 at 18 02 28](https://user-images.githubusercontent.com/39112974/52657466-a6fae500-2ef0-11e9-8074-531cada89bf0.jpg)

This happens with the other 2 deals as well. Same behaviour.

This is a matter of where you are positioning the marker to where the page must scroll down.

Please make sure that the tile of the deal is visible when I click on any of them and it scrolls down to the deal. It looks strange experiencing the page scrolling down and stopping at a point with no title.

**Comment by buckwierd** [comment]
I know. It’s because of the sticky header. The title is there. It the sticky header is covering it. 

As I already mentioned I wanted from the beginning to build proper deals pages but you guys didn’t wanted it. 

Since I knew that discussions like this will come up, here’s my plan for the future:
1. You will trust me in regards to decisions like this
2. In the most of the cases related to design I know what I’m talking about => You will trust me
3. I’m not part of the team to do shit => You’ll have to trust me again

Since everything comes down to trust, I won’t allow it in the future to interfere in plans like this, for two simple reasons:
1. It’s a waste of time to do something twice, only because someone that is not a designer didn’t cooperated
2. Working twice on the same task keeps us from moving forward fast

PS: Please don’t ask now if we can get rid of the sticky header, because we can’t. We need it from a UX perspective.

**Comment by RohrerHope** [comment]
Hi.

I appreciate your passion and want to clarify something:

1. This has never been about trust.
1. I remember when we had the discussion about the deals page and back the decision was mostly made to not delay any launch of W2.0. Now that we are live, we have time to address elements like this.
1. I have talked in the past about moving fast, so of course, I agree with it. This is especially true now that our W2.0 is up and running. @lcoenen Issues and bugs need to be tackled quickly, and any improvements to bring to the platform need to be focused on UX, UI and features that can have a huge impact on revenue generation.

Let's do this.

**Comment by lcoenen** [comment]
@buckwierd We agreed on not wasting time on a legal page for efficiency reason. You guys were the want that pushed for the launch. You could have made a very fancy legal page that nobody will read, but maybe our time would have been better used in improving actual features. I understand this frustration, but I refuse to be heard I "did not collaborated".

**Comment by buckwierd** [comment]
As this will be resolved with the new deals pages, the issue will be closed.
