### ISSUE TITLE
Highlight contact button to make it easier for users to find it

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#69]
There was a comment from Aoife about the Contact button not been easy to find.

### Here's how it looks today

![contact button without a border](https://user-images.githubusercontent.com/39112974/52775924-a66d6600-3038-11e9-92ff-fd3d9f34214b.jpg)

### Here's how it looks when I: 1) remove padding, 2) add border-style: solid, and 3) add border-width: 1px in the element: .Button__inlineTextButton__3IeDs

![contact button with a border](https://user-images.githubusercontent.com/39112974/52776042-dd437c00-3038-11e9-84cd-ac36940d9ab3.jpg)

We would also need to adjust the hover effect when we position the mouse to click it.

**This is a proposal.**

**Comment by buckwierd** [comment]
@RohrerHope Aoife never mentioned the contact host button. We'll talk about this on Friday.

**Comment by RohrerHope** [comment]
@buckwierd 

![aoife message contact button](https://user-images.githubusercontent.com/39112974/52788751-d0835000-3059-11e9-9496-f1fb2f585c5c.jpg)

**Comment by buckwierd** [comment]
@RohrerHope I know and if you think back this is the question related to "Contact", from your own "Ideas for QUestions" checklist: "Contact the Whichost team by email/phone".

It doesn't matter if this was a confusion because it was a good one. We'll change the colors and adapt the buttons after we agreed on one style. Please look at this website www.gaest.com and see how they solved the problem. They only use their main color and it looks great. These are the guys that Airbnb bought a couple of weeks ago.

https://luckey.fr/en/ does the same but they're also combining their main color with ghost buttons (the ones with the white frame). This company was also bought by Airbnb a couple of weeks ago.

**Comment by RohrerHope** [comment]
@buckwierd 

Both Gaest and Luckey manage their buttons great and I enjoyed both. I also appreciate that both of them have their buttons always on the main brand colour.

**Comment by buckwierd** [comment]
Both "Contact" H links at the top and bottom of the L page were transformed into ghost buttons. 

Top area:
[https://drive.google.com/open?id=1yxy-l6vkNF9ibVL_TJ0uRWOOZUKqoDKC](url)

Bottom area:
[https://drive.google.com/open?id=130_5_xAAWXZyd1SL3hERHVJLnLnFX65E](url)

@lcoenen was pushed on 4-adjust-the-static-centent. Feel free to close the issue after it was pushed to master.

**Comment by RohrerHope** [comment]
I confirm this are okay in Staging. 👍 

BTW, the drive URLs you entered in your last comment don't work when clicking on them. They go to an empty page. I had to copy and paste them.

Thanks.

**Comment by lcoenen** [comment]
This will be pushed to master
