### ISSUE TITLE
Improve the contact information for changing payment information

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#88]
If your payment information in your account is already set up, there is no easy way to change it.

This is what you see when you want to change it:

![contact to change payment information](https://user-images.githubusercontent.com/39112974/53168034-9bcf4580-35d1-11e9-878f-6ed06afa8afa.jpg)

The text there says: "You’ve already entered your payment details. If you want to change your payment details, please contact the marketplace admins."

The idea is to improve that message so we can say:
"You’ve already entered your payment details. If you want to change your payment details, please contact Whichost by clicking here." (where clicking here has a hyperlink for a mailto:support@whichost.com?subject=Payment Information Change.

👍

**Comment by RohrerHope** [comment]
This a patch, since it doesn't provide a solid solution because once they contact us, we will have to reply to them asking all the details of the new payment information.

So if Sharetribe does not implement an easy way for users to change this information, we will need to eventually implement a smart solution where when users ask to change the payment information, we immediately ask them for all the info we need to make that change.

**Comment by lcoenen** [comment]
It is weird that they cannot modify information. I might be able to fix that in the Frontend.

**Comment by RohrerHope** [comment]
Information related to this:

Sharetribe just replied confirming that to change the payment information we need to jump into our Stripe account and change the customer's information there.

Quoting Sharetribe:
"
Hi there,

Unfortunately, you can't edit the payment information from Console but you can do it directly from the Stripe dashboard (https://dashboard.stripe.com/login). Log in to your Stripe account and go to 'Connect' -> 'Accounts'. Select the user whose information you want to edit. Then you can e.g. edit the personal information in 'Identity' section or add a new bank account form 'External accounts' section. 

Best,
Jenni from Sharetribe
"

**Comment by buckwierd** [comment]
We’ll have a huge legal issue as per the data protection regulations, if we ask users to send us their full bank account details. 

Users need to be able to edit their payment details on their own. I know this because while I was with Airbnb, we had to delete emails and messages when someone mentioned their bank account details. In addition to this we had to send a special request to a dedicated internal SPAM team so they can delete every single proof of those bank details from the Airbnb database. 

The only legal safe solution is to provide the users the option to change it themselves. This is then connected with a more sophisticated coding need, since the users should not be able to change the payment details if they have an upcoming booking or if a booking is over but no reviews were left (in case something went wrong and we have to refund). 

Providing them the option to change their payment details sounds easy but it takes loads of work to implement it in a safe way. 

I can give more context on this tomorrow in the meeting.

**Comment by RohrerHope** [comment]
Thanks for the info.

However, we can't wait until we have a proper payment information update system. That will take a long time and we need to continue moving.

So basically we need to figure out the best way to manage this, and very soon (like in the next few days).

**Comment by RohrerHope** [comment]
**Expanding this**

The only information we need to update the payment information is the IBAN.

IBANs are extremely secure and sharing that information with anyone is not risky, because nothing can be done with only an IBAN. Actually, you can only transfer to that IBAN, and that's it.

**Idea**

Taking that under consideration, that we only need an IBAN, we could have a process in which we call the P by phone to ask for that information. As he gives the IBAN we then update the Stripe information and that's it, it's only recorded where it must be recorded, inside Stripe.

That's if we don't want to have that information in a digital format like an email, form, text message, etc.

**Comment by RohrerHope** [comment]
**More on this**

As I research and think more about this I believe for now there's only one safe solution for us:

When publicans want to claim their listing, they will need to create their own account inside Whichost, we will transfer the content to them, and they can create the listing with our content, or they can choose to use a different one.

Once they create their account and L their pub, we then close the L that Whichost manages.

Changing the account holder information is not enough since we won't be able to change the payment information easily.

**Comment by RohrerHope** [comment]
As agreed guys, we are okay with collecting the IBAN so please let's move forward with this issue and update the message. 👍 

As we talked, let's define the Subject of the email and add information in the body in which we put a small template for them to add the IBAN.

Thanks.

**Comment by RohrerHope** [comment]
Here's **an idea 💡 ** for the hyperlink mailto:

mailto:support@whichost.com?subject=Payment%20Information%20Change&body=Please%20update%20the%20payment%20information%20to%20the%20following%20IBAN:%0A%0AThe%20name%20of%20the%20pub%20listed%20is:%0A%0AThank%20you.%20%0A

This will translate into:

Subject: Payment Information Change
Body:
Please update the payment information to the following IBAN: 

The name of the pub listed is:

Thank you.

**Comment by lcoenen** [comment]
Curiously enough, it's not trivial to add a link inside a translation. I could hack it but I preferred to ask share tribe how to do it properly

**Comment by RohrerHope** [comment]
Sounds good. Thanks.

**Comment by lcoenen** [comment]
Still ongoing.

**Comment by RohrerHope** [comment]
Please review this issue.

**Comment by buckwierd** [comment]
@lcoenen what's the status with this one? There is no update from your side since 1st Mar. Can we do anything to assist you?

**Comment by RohrerHope** [comment]
I can't test this issue now. Please someone else test it.

**Comment by lcoenen** [comment]
Ok, we cannot test it properly, we need more time on this. The people can actually contact us since the only people who will see it will already have our email address. This will be done by next launch.

**Comment by lcoenen** [comment]
To do: check if the contact link is shown correctly after adding payement methods.

**Comment by lcoenen** [comment]
I am working on it. 

**Work on it**:

- Place the card in `ongoing` column
- Tag it with `ongoing`

**Comment by lcoenen** [comment]
**What have been done**: Add the mailto: link to the message shown right after payement infos have been entered.
**Pushed to**: `staging`
**Tag somebody**: @RohrerHope 

**Asking for validation**: 

- Check on mobile and on desktop if the issue have been correctly fixed.
- If everything is correct, move the card to accepted column.
- If the issue isn't fixed, re-open the comment clearly what the problem is and what is the desired result. 
- Move the card to have issues column.
- Merge (or express approval in) the corresponding PR if needed. Move the card to the launch column.

![image](https://user-images.githubusercontent.com/1237971/56220811-fbd9e980-6060-11e9-8cad-37a3ddab8112.png)

**Comment by RohrerHope** [comment]
@lcoenen  can you provide us with an account that has payment settings added in staging? So that we can test this properly.

Thanks 👍

**Comment by lcoenen** [comment]
@RohrerHope You can use The Cotton Ball (https://whichost-frontend-staging.herokuapp.com/l/the-cotton-ball-cork/5c0a5516-6f5b-45b1-bfb6-22b157f77d8a)

**Comment by RohrerHope** [comment]
> @RohrerHope You can use The Cotton Ball (https://whichost-frontend-staging.herokuapp.com/l/the-cotton-ball-cork/5c0a5516-6f5b-45b1-bfb6-22b157f77d8a)

Thanks. But I need to log in as the Cotton Ball in order to test this issue.

I don't have the login information for that listing in staging. Can you share that with me, please?

Thanks 👍
