### ISSUE TITLE
[Deals Page] Bullet points for elements in "How it works"

### ISSUE THREAD

**Issue by RohrerHope** [Whichost/frontend#99]
The elements in the image should be bullet points and not simple paragraphs. As they are designed like this in the Google Doc. This observation applies for both the Birthday deal page and the employees benefit page.

![Screen Shot 2019-03-17 at 18 58 08](https://user-images.githubusercontent.com/39112974/54496396-bf429300-48e6-11e9-9433-37900d964e8f.jpg)

Bullet points, not numbers.

**Comment by buckwierd** [comment]
Fixed it in `marketplaceFonts.css` by changing the font size to 16px 
`--marketplaceDefaultFontStyles: {
    font-family: 'Lato', sans-serif;
    font-weight: var(--fontWeightMedium);
    font-size: 16px;
    line-height: 24px;
    letter-spacing: -0.1px;
    /* No margins for default font */

    @media (--viewportMedium) {
      font-size: 16px;
      line-height: 24px;
    }
  }`

FYI
Since this is a global setting, it might have changed at the same time other unordered lists. Normally this is not an issue (good to know just in case).

@RohrerHope  @lcoenen  was pushed over `set-up.deal-pages`

**Comment by lcoenen** [comment]
Pushed to staging

**Comment by RohrerHope** [comment]
Approved for both the Birthday Deal and the Employees Benefit pages. 👍
